author: Dr. Mehdi Benkhadra
title: Dr. Mehdi Benkhadra MD, PhD
email: contact@drmehdibenkhadra.fr
description: > # this means to ignore newlines until "baseurl:"
  Traitement de la calvitie
url: "https://drmehdibenkhadra.fr" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/drmehdibenkhadra-fr" # the subpath of your site, e.g. /blog
timezone: Europe/Zurich

color:
  primary-dark: '#000000'
  links: '#c2ae8c'
  intro-bg: '#c2ae8c'
  intro-fg: '#1c2251'

# Footer settings
footer: Dr. Mehdi Benkhadra

social:
  - title: linkedin
    url: https://www.linkedin.com/in/mehdi-benkhadra-md-phd-574819196/

# Build settings
markdown:   kramdown
permalink:  pretty

collections:
  - sections

# Google Analytics
google_analytics: UA-149542574-1

plugins:
  - jekyll-sitemap
#  - jekyll-remote-theme
  - jekyll-seo-tag
