author: Dr. Mehdi Benkhadra
title: Dr. Mehdi Benkhadra, MD, PhD
email: contact@drmehdibenkhadra.fr
description: > # this means to ignore newlines until "url:"
  Traitement de la calvitie
  - Greffe de cheveux
  - Dijon 
url: "https://drmehdibenkhadra.fr" # the base hostname & protocol for your site, e.g. http://example.com
# the subpath of your site, e.g. /blog
baseurl: "/drmehdibenkhadra-fr"
# currently left on this default so the Github Pages preview works
# use the " -b '' " parameter to use as a a root-website, e.g.:
#  - for serving on the local network as a root-website:
#    > bundle exec jekyll serve -H 0.0.0.0 -b ''
#  - for build the release for root on the domain:
#    > JEKYLL_ENV=production bundle exec jekyll build -d _upload -b ''
logo: "/img/intro-bg.png"
timezone: Europe/Paris

address:
  streetAddress: "14 Rue du Cap Vert"
  postalCode: "21800"
  addressLocality: "Quetigny"
  addressCountry: "fr"

phone: "+33-9-80-45-98-14"


color:
  primary-dark: '#000000'
  links: '#c2ab8b'
  intro-bg: '#c0a987'
  intro-fg: '#2b2765'

# Footer settings
footer: Dr. Mehdi Benkhadra

social:
  - title: linkedin
    url: https://www.linkedin.com/in/mehdi-benkhadra-md-phd-574819196/

# Build settings
markdown:   kramdown
permalink:  pretty

collections:
  - sections

# Google Analytics
google_analytics: UA-149542574-1

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
#  - jekyll-remote-theme

# stuff on the repo but not on the final website
exclude:
  - LICENCE
  - README.md
